language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t thilina9718/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thilina9718/react-test npm test

after_success:
  - docker build -t thilina9718/multi-client ./client
  - docker build -t thilina9718/multi-nginx ./nginx
  - docker build -t thilina9718/multi-server ./server
  - docker build -t thilina9718/multi-worker ./worker
  - echo "$DOCKER_PASSWORd" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thilina9718/multi-client
  - docker push thilina9718/multi-nginx
  - docker push thilina9718/multi-server
  - docker push thilina9718/multi-worker


